[theme]
# Primary accent color for interactive elements.
primaryColor = "#cce8e2"

# Background color for the main content area.
backgroundColor = "#cce8e2"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#66b9a7"

# Color used for almost all text.
textColor = "black-grey"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"